/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


@interface NXTFPage : NSObject <TBase, NSCoding> {
  int32_t __pageNo;
  int32_t __pageSize;
  int64_t __total;

  BOOL __pageNo_isset;
  BOOL __pageSize_isset;
  BOOL __total_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=pageNo, setter=setPageNo:) int32_t pageNo;
@property (nonatomic, getter=pageSize, setter=setPageSize:) int32_t pageSize;
@property (nonatomic, getter=total, setter=setTotal:) int64_t total;
#endif

- (id) init;
- (id) initWithPageNo: (int32_t) pageNo pageSize: (int32_t) pageSize total: (int64_t) total;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) pageNo;
- (void) setPageNo: (int32_t) pageNo;
#endif
- (BOOL) pageNoIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageSize;
- (void) setPageSize: (int32_t) pageSize;
#endif
- (BOOL) pageSizeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) total;
- (void) setTotal: (int64_t) total;
#endif
- (BOOL) totalIsSet;

@end

@interface NXTFDevice : NSObject <TBase, NSCoding> {
  NSString * __deviceId;
  NSString * __deviceName;
  NSString * __osName;

  BOOL __deviceId_isset;
  BOOL __deviceName_isset;
  BOOL __osName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
@property (nonatomic, retain, getter=deviceName, setter=setDeviceName:) NSString * deviceName;
@property (nonatomic, retain, getter=osName, setter=setOsName:) NSString * osName;
#endif

- (id) init;
- (id) initWithDeviceId: (NSString *) deviceId deviceName: (NSString *) deviceName osName: (NSString *) osName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceName;
- (void) setDeviceName: (NSString *) deviceName;
#endif
- (BOOL) deviceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) osName;
- (void) setOsName: (NSString *) osName;
#endif
- (BOOL) osNameIsSet;

@end

@interface NXTFReqHeader : NSObject <TBase, NSCoding> {
  int32_t __appType;
  NSString * __appVersion;
  NSString * __token;
  int64_t __timestamp;
  NSString * __nonce;
  NSString * __signature;
  int64_t __userId;
  NXTFDevice * __device;
  int32_t __appKind;
  NSString * __appMark;

  BOOL __appType_isset;
  BOOL __appVersion_isset;
  BOOL __token_isset;
  BOOL __timestamp_isset;
  BOOL __nonce_isset;
  BOOL __signature_isset;
  BOOL __userId_isset;
  BOOL __device_isset;
  BOOL __appKind_isset;
  BOOL __appMark_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=appType, setter=setAppType:) int32_t appType;
@property (nonatomic, retain, getter=appVersion, setter=setAppVersion:) NSString * appVersion;
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) int64_t timestamp;
@property (nonatomic, retain, getter=nonce, setter=setNonce:) NSString * nonce;
@property (nonatomic, retain, getter=signature, setter=setSignature:) NSString * signature;
@property (nonatomic, getter=userId, setter=setUserId:) int64_t userId;
@property (nonatomic, retain, getter=device, setter=setDevice:) NXTFDevice * device;
@property (nonatomic, getter=appKind, setter=setAppKind:) int32_t appKind;
@property (nonatomic, retain, getter=appMark, setter=setAppMark:) NSString * appMark;
#endif

- (id) init;
- (id) initWithAppType: (int32_t) appType appVersion: (NSString *) appVersion token: (NSString *) token timestamp: (int64_t) timestamp nonce: (NSString *) nonce signature: (NSString *) signature userId: (int64_t) userId device: (NXTFDevice *) device appKind: (int32_t) appKind appMark: (NSString *) appMark;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) appType;
- (void) setAppType: (int32_t) appType;
#endif
- (BOOL) appTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appVersion;
- (void) setAppVersion: (NSString *) appVersion;
#endif
- (BOOL) appVersionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

#if !__has_feature(objc_arc)
- (int64_t) timestamp;
- (void) setTimestamp: (int64_t) timestamp;
#endif
- (BOOL) timestampIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nonce;
- (void) setNonce: (NSString *) nonce;
#endif
- (BOOL) nonceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) signature;
- (void) setSignature: (NSString *) signature;
#endif
- (BOOL) signatureIsSet;

#if !__has_feature(objc_arc)
- (int64_t) userId;
- (void) setUserId: (int64_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NXTFDevice *) device;
- (void) setDevice: (NXTFDevice *) device;
#endif
- (BOOL) deviceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) appKind;
- (void) setAppKind: (int32_t) appKind;
#endif
- (BOOL) appKindIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appMark;
- (void) setAppMark: (NSString *) appMark;
#endif
- (BOOL) appMarkIsSet;

@end

@interface NXTFRespHeader : NSObject <TBase, NSCoding> {
  int32_t __status;
  NSString * __msg;

  BOOL __status_isset;
  BOOL __msg_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=status, setter=setStatus:) int32_t status;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
#endif

- (id) init;
- (id) initWithStatus: (int32_t) status msg: (NSString *) msg;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) status;
- (void) setStatus: (int32_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

@end

@interface NXTFBaseConstants : NSObject {
}
@end
