/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"

#import "MtReq.h"
#import "MtResp.h"

@protocol NMTFEmart <NSObject>
- (NMTFGetMtBannersResp *) getMtBanners: (NMTFGetMtBannersReq *) req;  // throws TException
- (NMTFGetMtProCatsResp *) getMtProCats: (NMTFGetMtProCatsReq *) req;  // throws TException
- (NMTFGetMtMersResp *) getMtMers: (NMTFGetMtMersReq *) req;  // throws TException
- (NMTFGetMtMerInfoResp *) getMtMerInfo: (NMTFGetMtMerInfoReq *) req;  // throws TException
- (NMTFGetMtMerStoresResp *) getMtMerStores: (NMTFGetMtMerStoresReq *) req;  // throws TException
- (NMTFGetMtProsResp *) getMtPros: (NMTFGetMtProsReq *) req;  // throws TException
- (NMTFGetMtProInfoResp *) getMtProInfo: (NMTFGetMtProInfoReq *) req;  // throws TException
- (NMTFFindMtMerProsResp *) findMtMerPros: (NMTFFindMtMerProsReq *) req;  // throws TException
- (NMTFGetMtShipAddsResp *) getMtShipAdds: (NMTFGetMtShipAddsReq *) req;  // throws TException
- (NMTFEditMtShipAddResp *) editMtShipAdd: (NMTFEditMtShipAddReq *) req;  // throws TException
- (NMTFGetMtCartProsCntResp *) getMtCartProsCnt: (NMTFGetMtCartProsCntReq *) req;  // throws TException
- (NMTFGetMtCartProsResp *) getMtCartPros: (NMTFGetMtCartProsReq *) req;  // throws TException
- (NMTFEditMtCartProsResp *) editMtCartPros: (NMTFEditMtCartProsReq *) req;  // throws TException
- (NMTFCreateMtOrderResp *) createMtOrder: (NMTFCreateMtOrderReq *) req;  // throws TException
- (NMTFCancelMtOrderResp *) cancelMtOrder: (NMTFCancelMtOrderReq *) req;  // throws TException
- (NMTFDelMtOrderResp *) delMtOrder: (NMTFDelMtOrderReq *) req;  // throws TException
- (NMTFPrePayMtOrderResp *) prePayMtOrder: (NMTFPrePayMtOrderReq *) req;  // throws TException
- (NMTFPayMtOrderResp *) payMtOrder: (NMTFPayMtOrderReq *) req;  // throws TException
- (NMTFReceiptMtProsResp *) receiptMtPros: (NMTFReceiptMtProsReq *) req;  // throws TException
- (NMTFReqMtRefundResp *) reqMtRefund: (NMTFReqMtRefundReq *) req;  // throws TException
- (NMTFGetUserOrderListResp *) getUserOrderList: (NMTFGetUserOrderListReq *) req;  // throws TException
- (NMTFGetPayBanksResp *) getPayBanks: (NMTFGetPayBanksReq *) req;  // throws TException
- (NMTFPreBindBankCardResp *) preBindBankCard: (NMTFPreBindBankCardReq *) req;  // throws TException
- (NMTFBindBankCardResp *) bindBankCard: (NMTFBindBankCardReq *) req;  // throws TException
- (NMTFGetMtBindingsResp *) getMtBindings: (NMTFGetMtBindingsReq *) req;  // throws TException
- (NMTFGetMtOrderDetailResp *) getMtOrderDetail: (NMTFGetMtOrderDetailReq *) req;  // throws TException
@end

@interface NMTFEmartClient : TBaseClient <NMTFEmart> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface NMTFEmartProcessor : NSObject <TProcessor> {
  id <NMTFEmart> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithEmart: (id <NMTFEmart>) service;
- (id<NMTFEmart>) service;
@end

@interface NMTFMtApiConstants : NSObject {
}
@end
